refactor: control default entities display resolution
firstof9/openevse pull request #249
Opened 2023-08-16 13:51 UTC by tschiex

Just some minor adjustments to some sensor entities that showed a large number of digits after the decimal in the default display. There may be more sensors to "tame" than the ones I changed (among non active ones possibly).

I notice, as I create this PR, that the VERSION = "1.0.0" has been changed to VERSION = "2.1.26" and this is probably a change that should be thrown away (it likely comes from tests I did on my HA instance before submitting the PR).

Thanks to all contributors for their efforts!

2023-08-16 15:44 UTC, firstof9 requested changes

2023-08-16 15:44 UTC, firstof9 commented on custom_components/openevse/const.py
> +VERSION = "2.1.26"
```suggestion
VERSION = "1.0.0"
```

This change isn't needed as the github workflow updates the version on release.

2023-08-16 15:50 UTC, firstof9 commented
Don't worry about the tests, I need to fix them.

2023-08-17 07:24 UTC, tschiex commented
I'm a newbie when it comes to PR management on GitHub. I reverted the version back to its original format; committed and pushed. It seems to be automagically inserted in the PR. Just tell me if I'm doing wrong (my apologies if so).

2023-08-17 16:11 UTC, firstof9 commented
You're doing fine, that's exactly how you do it.

2023-08-17 16:11 UTC, firstof9 approved these changes

2023-08-17 16:23 UTC, merged

2023-08-17 16:24 UTC, firstof9 commented
Thanks!